### ISSUE TITLE
Use a more efficient format for device trees (JSDT).

### ISSUE THREAD

**Issue by christinaa** [b-man/xBoot#2]
**This is taken from an old project from 2013, which is the main reason your project has JSMN as a dangling dependency. It _has not been modified since_, provided as is, and no support or warranty is implied.**

This is a parser for a device tree format called JSDT which is a much better format than XML device trees that you currently use (which is why JSDT was written). It is provided under GPLv3 as long as the topmost copyright notice between long lines of `=====` is retained. The variation of the JSMN parser you're using is not actually suited for JSDT, I am also providing a compatible JSMN parser (you will need to change the header file slightly to add support for the special node `JSMN_CHILDREN_TOKEN`).

**Parser:**
http://crna.cc/_JS_device_tree.c
http://crna.cc/_jsmn.c

**Example device tree:**
http://crna.cc/_JSDT_Example.jsdt

You can use it as a drop in replacement where you do DT loading (around `CONFIG_DT_SUPPORT_XML` probably), it should fit in well considering it was part of the codebase that a lot of this bootloader is based on. I think the Img3 parser you're using even has a tag for it (`jsdt`):

https://github.com/b-man/xBoot/blob/bbd02e85d49eabb76ef7b901a96f4d0f685a458a/include/boot/image3.h#L58

**Comment by b-man** [comment]
@christinaa 

Thank you for this contribution Kristina, It's greatly appreciated.
The only question that I have for utilizing this code in xBoot
is that if I incorporate this code into the loader, am I not required to 
relicense/dual license xBoot under the GPLv3? Would it be possible
to make this available under the LGPLv3?

**Comment by christinaa** [comment]
Yes, GPLv3 will mean all of the code in the project, when compiled inherits (is poisoned by) the GPLv3 code licensed code since it's compatible with APSL/modified BSD licenses.

As far as LGPLv3 goes, this will suffice, since your project contains a lot of my copyrighted code already, keep in mind that this also disambiguate the licensing terms of that code. So as per your request:

**I hereby license all of my current works included in the project as LGPLv3, as well as all JSDT related components linked above, which can be used either under the terms of GPLv3 or LGPLv3. This shall come in effect at the time of this writing (11:13 PDT, 03 Nov 2017).**

**Comment by christinaa** [comment]
Please keep in mind that the conditions of retaining the topmost header in its unmodified form still apply to JSDT code. You are free to add your own above it, as long as it remains somewhere in the source code file. Obviously device trees in JSDT format wouldn't really be considered derivative works so that doesn't apply to them.

As to answer your question regarding re-licensing, because of the disambiguation, I believe xBoot is currently LGPLv3, with or without JSDT, unless you're unhappy with LGPLv3 and want me to license my old code out which the project that your project is based on, but personally I prefer it being under a "free" license.

Also, I do apologize for replying to your followup late, been busy.

**Comment by b-man** [comment]
@christinaa 

> As to answer your question regarding re-licensing, because of the disambiguation, I believe xBoot is currently LGPLv3, with or without JSDT, unless you're unhappy with LGPLv3 and want me to license my old code out which the project that your project is based on, but personally I prefer it being under a "free" license.

Can you elaborate on that claim that xBoot is LGPLv3?

All of the code under lib/crt is mostly borrowed from OpenBSD, NetBSD, FreeBSD, public domain,
 or my own. The shell, device interface, bsp layer, drivers, and the nvram variable emulation are my own creations. Everything uder core/* is my own. The tlsf allocator is provided by a third party under the BSD license. The build system is my own. The SHA1 code was provided under public domain, and the PRNG was implemented from pseudo code in a research paper that was credited. The arm-specific memory set/move/copy/zero code was from NetBSD and OpenBSD. The arm compiler intrinsic functions  are from Tianocore. The arm initialization and exception handling code as well as almost everything under include/boot+lib/boot and lib/debug was copied over from winocm 's GenericBooter and MachBoot. 

I know that lib/boot/boot.c originally included your XML parsing code, of which has since been
removed since moving over to the JSDT parser that you kindly provided - unless I'm missing
something else there.

If you can give me a specific list of files that include your code I'll gladly prepend those
files with your credit and relicense them as such. Everything that I copied from MachBoot and GenericBooter was copied with their copyright notices in tact.

**Comment by winocm** [comment]
Please remove me from this conversation, I am not involved in this project nor have I been for years now.

**Comment by b-man** [comment]
Sorry for bringing you into this @winocm , I'm just pointing out to @christinaa that I borrowed code from your old project. I'm just pointing out that the assertion that a majority of xBoot is a derivative work of @christinaa's is flawed.

**Comment by christinaa** [comment]
I don't really have time to compile a list of what's derivative or what's non-derivative and finding the old code to diff against, but I quickly glanced over it and I know it. I'm not going to do anything about it regardless.
